repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--profile=black]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.1
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.3
    hooks:
      - id: uv-export
        args: ["--no-hashes", "--frozen", "--output-file=requirements.txt"]

  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        entry: uv run pytest --maxfail=1 --disable-warnings -q
        language: system
        pass_filenames: false
        always_run: true
