
services:
  # MLflow Tracking Server - Pull from Docker Hub
  mlflow:
    image: ${DOCKER_HUB_USERNAME:-zanjesud}/mlops-mlflow:${IMAGE_TAG:-latest}
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns
      - ./logs:/app/logs
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    networks:
      - mlops-network
    restart: unless-stopped

  # FastAPI Application - Pull from Docker Hub
  api:
    image: ${DOCKER_HUB_USERNAME:-zanjesud}/mlops-api:${IMAGE_TAG:-latest}
    ports:
      - "8000:8000"
    volumes:
      - ./mlruns:/app/mlruns
      - ./logs:/app/logs
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
    networks:
      - mlops-network
    restart: unless-stopped

  # Streamlit UI - Pull from Docker Hub
  ui:
    image: ${DOCKER_HUB_USERNAME:-zanjesud}/mlops-ui:${IMAGE_TAG:-latest}
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    networks:
      - mlops-network
    restart: unless-stopped

  # Prometheus for monitoring
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - mlops-network
    restart: unless-stopped

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - mlops-network
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:

networks:
  mlops-network:
    driver: bridge