version: '3.8'

services:
  # MLflow Tracking Server
  mlflow:
    image: python:3.11-slim
    working_dir: /app
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
    command: >
      sh -c "pip install uv && uv pip install --system . && 
             mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlruns/mlflow.db"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    networks:
      - mlops-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8501:8501"
    volumes:
      - ./mlruns:/app/mlruns
      - ./logs:/app/logs
    environment:
      - API_URL=http://localhost:8000
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
    networks:
      - mlops-network
    restart: unless-stopped

  # # FastAPI Application
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.api
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./mlruns:/app/mlruns
  #     - ./logs:/app/logs
  #   environment:
  #     - MLFLOW_TRACKING_URI=http://mlflow:5000
  #   depends_on:
  #     - mlflow
  #   networks:
  #     - mlops-network
  #   restart: unless-stopped

  # # Streamlit UI
  # ui:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.ui
  #   ports:
  #     - "8501:8501"
  #   environment:
  #     - API_URL=http://api:8000
  #   depends_on:
  #     - api
  #   networks:
  #     - mlops-network
  #   restart: unless-stopped

  # Prometheus for monitoring
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - mlops-network
    restart: unless-stopped

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - mlops-network
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:

networks:
  mlops-network:
    driver: bridge 