name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]

permissions:
  contents: read
  pull-requests: write

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: pip install uv

      - name: Create virtual environment
        run: uv venv .venv

      - name: Install dependencies
        run: uv pip install  pytest pytest-cov ruff black isort mypy pre-commit

      - name: Create necessary directories
        run: |
          mkdir -p logs
          mkdir -p models/production_model
          mkdir -p data/processed

      # - name: Run pre-commit hooks
      #   run: uv run pre-commit run --all-files

      - name: Lint with ruff
        run: uv run ruff check . --select E,F,W

      - name: Check code format
        run: |
          uv run black --check .
          uv run isort --check-only .
          uv run mypy .

      - name: Run unit tests
        run: uv run pytest tests/test_api.py -v --cov=api --cov-report=xml --cov-report=html

      # Integration tests are skipped in CI as they require running services
      # Run them locally with: docker-compose up -d && pytest tests/integration/ -v

      - name: Upload coverage reports as artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-reports-${{ matrix.python-version }}
          path: |
            coverage.xml
            htmlcov/
          retention-days: 30
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}


